# Generated by Django 4.1.5 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betteretf", "0003_alter_fund_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yahooraw",
            name="ticker",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
